In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import os
import cv2
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the image dataset and convert to numpy array
DATADIR = "/content/drive/MyDrive/face detection"
CATEGORIES = ["with_mask", "without_mask"]

# Define image size
IMG_SIZE = 100

# Function to load and preprocess the images
def load_data():
    data = []
    labels = []
    for category in CATEGORIES:
        folder = os.path.join(DATADIR, category)
        files = os.listdir(folder)[:1500]
        for file in files:
            img_path = os.path.join(folder, file)
            try:
                img = cv2.imread(img_path)
                img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
                data.append(img)
                labels.append(CATEGORIES.index(category))
            except Exception as e:
                pass
    data = np.array(data).reshape(-1, IMG_SIZE * IMG_SIZE)
    labels = np.array(labels)
    # Shuffle the dataset
    shuffle_idx = np.random.permutation(len(data))
    data = data[shuffle_idx]
    labels = labels[shuffle_idx]
    return data, labels

# Load the dataset
X, y = load_data()

# Split the dataset into training and testing sets
split_idx = int(0.8 * len(X))
X_train, X_test = X[:split_idx], X[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]

# Logistic regression
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)
lr_cm = confusion_matrix(y_test, lr_pred)
print("Logistic Regression Accuracy:", lr_acc)
print("Logistic Regression Confusion Matrix:\n", lr_cm)

# Decision tree
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)
dt_cm = confusion_matrix(y_test, dt_pred)
print("Decision Tree Accuracy:", dt_acc)
print("Decision Tree Confusion Matrix:\n", dt_cm)

# Support vector machine
svm = SVC()
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)
svm_cm = confusion_matrix(y_test, svm_pred)
print("Support Vector Machine Accuracy:", svm_acc)
print("Support Vector Machine Confusion Matrix:\n", svm_cm)

# K-nearest neighbors
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)
knn_acc = accuracy_score(y_test, knn_pred)
knn_cm = confusion_matrix(y_test, knn_pred)
print("K-Nearest Neighbors Accuracy:", knn_acc)
print("K-Nearest Neighbors Confusion Matrix:\n", knn_cm)

# Random forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)
rf_cm = confusion_matrix(y_test, rf_pred)
print("Random Forest Accuracy:", rf_acc)
print("Random Forest Confusion Matrix:\n", rf_cm)

Logistic Regression Accuracy: 0.72
Logistic Regression Confusion Matrix:
 [[203  99]
 [ 69 229]]
Decision Tree Accuracy: 0.7766666666666666
Decision Tree Confusion Matrix:
 [[233  69]
 [ 65 233]]
Support Vector Machine Accuracy: 0.8716666666666667
Support Vector Machine Confusion Matrix:
 [[257  45]
 [ 32 266]]
K-Nearest Neighbors Accuracy: 0.8133333333333334
K-Nearest Neighbors Confusion Matrix:
 [[213  89]
 [ 23 275]]
Random Forest Accuracy: 0.8633333333333333
Random Forest Confusion Matrix:
 [[257  45]
 [ 37 261]]
